
version: "3.8"

services:
  # Postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local