
version: "3.8"

services:
  # MySQL
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=testdb
    volumes:
      - mysql_data:/var/lib/mysql
      
  # Postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    volumes: 
      - postgres:/var/lib/postgresql/data

volumes:
  mysql_data:
  postgres:
    driver: local